# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Code Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run checkstyle
      run: mvn -B checkstyle:checkstyle
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: target/checkstyle-result.xml
    
  jacoco:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Run test to create jacoco.exec
          run: mvn test
        - name: Run Jacoco report goal
          run: mvn -B jacoco:report
        - name: Upload Jacoco report
          uses: actions/upload-artifact@v2
          with:
            name: jacoco-report
            path: target/site/jacoco/index.html
            retention-days: 2
